version: "3.7"
services:
  simulator-server:
    image: simulator-server
    container_name: simulator-server
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://simulator-etcd:2379
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "1212:1212"
    restart: always
    tty: true
    networks:
      - simulator-internal-network
  simulator-etcd:
    image: quay.io/coreos/etcd:v3.4.0
    container_name: simulator-etcd
    restart: always
    volumes:
      - simulator-etcd-data:/var/lib/etcd
    command: etcd --advertise-client-urls http://simulator-etcd:2379 --data-dir /var/lib/etcd --listen-client-urls http://0.0.0.0:2379 --initial-cluster-state new --initial-cluster-token tkn
    networks:
      - simulator-internal-network
volumes:
  simulator-etcd-data:
networks:
  simulator-internal-network:
    driver: bridge

